[package]
name = "pieStat"
version = "1.0.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.0"
image = "0.25.8"
tao = "0.34.3"
tray-icon = "0.21.1"
x11 = "2.18"  # or the latest version available
libc = "0.2"
x11rb = "0.13.2"
